name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - basicsr==1.4.2
    - albumentations==0.4.3
    - diffusers==0.11.1
    - pytorch_lightning==1.5.9
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark==0.1.5
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.3.0
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.6.0
    - gradio==3.20.0
    - torch-fidelity==0.3.0
    - transformers==4.27.4
    - torchmetrics==0.6.0
    - kornia==0.6.8
    - k-diffusion==0.0.14
    - webdataset==0.2.35
    - safetensors==0.3.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .